### ISSUE TITLE
maven repository doesn't have latest versions

### ISSUE THREAD

**Issue by andrey-ilinykh** [sclasen/akka-zk-cluster-seed#13]
The latest version maven has is 0.1.2. Is it possible to push later?

**Comment by sclasen** [comment]
maven central has up to 0.1.5 for the 2_11 version.  The upgrade to later
version of akka (2.4.0) doesnt support 2.10 afaict.

http://repo1.maven.org/maven2/com/sclasen/akka-zk-cluster-seed_2.11/

**Comment by vladislav-sidorovich** [comment]
Could you release version with this fix https://github.com/sclasen/akka-zk-cluster-seed/commit/40d6f7632621dd4fe3a8d221abc51bf6f56d8ca7

**Comment by sclasen** [comment]
I just pushed 0.1.6-SNAPSHOT to oss.sonatype.org, if you can try it out and think it works ok, I can ship 0.1.6 to maven central.

**Comment by vladislav-sidorovich** [comment]
Maven central is great. Thank you

**Comment by sclasen** [comment]
just pushed 0.1.6 to maven central and bumped master to 0.1.7, cheers!
