### ISSUE TITLE
Upgrade curator 

### ISSUE THREAD

**Issue by joprice** [sclasen/akka-zk-cluster-seed#17]
There's been lots of bug fixes since curator 2.8 https://cwiki.apache.org/confluence/display/CURATOR/Releases. Would a pr bumping the version be welcome?

**Comment by sclasen** [comment]
Yes please!

**Comment by joprice** [comment]
done in #18

**Comment by sclasen** [comment]
@joprice just pushed a 0.1.7-SNAPSHOT to oss.snoatype.org
