### ISSUE TITLE
Missing zookeeper authorization option

### ISSUE THREAD

**Issue by twisniewski** [sclasen/akka-zk-cluster-seed#4]
Currently it is impossible to use akka-zk-cluster-seed with zookeeper paths that require authorization.

Should we provide PR?

**Comment by sclasen** [comment]
Please do! :+1:

**Comment by sclasen** [comment]
@twisniewski Just published 0.1.2-SNAPSHOT to oss.sonatype

Can you try it out and give me a :+1:  :-1:  here?  If it looks good to you i'll push out 0.1.2 to maven central

Thanks!

**Comment by twisniewski** [comment]
:+1:  Snapshot works as expected.

**Comment by sclasen** [comment]
@twisniewski published 0.1.2 to maven central, should show up sometime soon. Thanks!
