### ISSUE TITLE
Issues with fast restart and ephemeral nodes

### ISSUE THREAD

**Issue by Alex-Ikanow** [sclasen/akka-zk-cluster-seed#7]
(Not sure if this is an akka-cluster issue or a zk-cluster-seed issue?)

I have a single node using akka-zk-cluster seed, and I am making the server port transient via

`.put("akka.remote.netty.tcp.port", "0")`

The first time, all is well. If I stop, wait 60s and then restart, all is well.

If I immediately restart then I get a continuous stream of:

`[default-akka.remote.default-remote-dispatcher-49] [akka.tcp://default@10.113.42.186:41006/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fdefault%4010.113.42.186%3A54564-0] Association with remote system [akka.tcp://default@10.113.42.186:54564] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://default@10.113.42.186:54564]] Caused by: [Connection refused: /10.113.42.186:54564]`

From tinkering with zookeeper-client it looks like the following happens:
* When the session that created an ephemeral node goes down, the node remains for 30 seconds. So there is a node in `/akka/cluster/seed/default` that points to the old transient port (:54564)
* When I restart within 30 seconds, the client reads the old ephemeral node and starts trying to connect to the old transient port
* It never errors out and goes back to reading the newer ephemeral node which has appeared in the meantime

**Comment by alexanderscott** [comment]
+1

**Comment by Alex-Ikanow** [comment]
(My workaround for now is to create my own ephemeral node on start and then wait for that to disappear before calling ZookeeperClusterSeed(...).join(), which seems to work)

**Comment by sclasen** [comment]
@Alex-Ikanow sorry for the delay, my github notifications were going to spam :(

there is now a timeout/reconnect logic which hopefully will nullify this issue

**Comment by Alex-Ikanow** [comment]
Thanks! I haven't yet dared to remove my workaround ... but th worksaround still occasionally failed when I restarted the whole cluster ... and it hasn't since I moved to the latest release on maven central, so it's looking promising! I'll have a play at some point this month and see how it works with that removed.

**Comment by pollycchang** [comment]
@sclasen I'm running into this problem with my cluster too. That's great that you have a fix for this issue. Will you be cutting the 0.1.5 release soon? Also, I noticed that you are now using Akka 2.4 in your build.sbt file. Will 0.1.5 be compatible with Akka 2.3 also? That's what I'm using in my project. Thanks!

**Comment by vkrot** [comment]
@sclasen , I also experience same issue in 0.1.5-SNAPSHOT version, a created a PR that removes ephemeral nodes with same hostPort address before creating a latch.
https://github.com/sclasen/akka-zk-cluster-seed/pull/10

**Comment by sclasen** [comment]
@vkrot thanks!  I pushed an updated 0.1.5-SNAPSHOT to oss.sonatype, can you try it out and let me know if it works as expceted, and I will then cut a 0.1.5 to maven central

**Comment by vkrot** [comment]
@sclasen , yes, it works. Thanks!

**Comment by sclasen** [comment]
pushed 0.1.5 to maven central, it should show ip in a bit!
